buildbuddy-redis: allow specifying tolerations and nodeSelector
buildbuddy-io/buildbuddy-helm pull request #80
Opened 2024-01-26 14:01 UTC by rszamszur

Follow-up for PR #71 - change did not include `buildbuddy-redis` Chart. Also while at it, allowing specifying `nodeSelector`.

2024-01-26 14:28 UTC, sluongng requested changes
Thanks for adding this.

One small update and I think this is good to merge.

2024-01-26 14:28 UTC, sluongng commented on charts/buildbuddy-redis/templates/deployment.yaml
> +      {{- end }}
I think an `if` clause is missing here

2024-01-26 14:39 UTC, rszamszur commented on charts/buildbuddy-redis/templates/deployment.yaml
> +      {{- end }}
:facepalm: Rookie mistake; Fixed

2024-01-29 11:00 UTC, sluongng approved these changes
I added a small fixup for documentation referring to the app / executor pods instead of the redis pods.

LGTM

2024-01-29 11:01 UTC, merged